// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCup8YO9SBMd5YZ97vgg82tcjtOEyySJx0',
    appId: '1:599526002290:web:ece1f3dcb38d0741357ceb',
    messagingSenderId: '599526002290',
    projectId: 'newappblog',
    authDomain: 'newappblog.firebaseapp.com',
    storageBucket: 'newappblog.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARuu4W2LL1sx7jVuBne9f8shoYlamgDg4',
    appId: '1:599526002290:android:50490816bf9b8662357ceb',
    messagingSenderId: '599526002290',
    projectId: 'newappblog',
    storageBucket: 'newappblog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChPNIJCFLjENnN2gvZf9imwJBP1TTf55c',
    appId: '1:599526002290:ios:d336424fa9667a24357ceb',
    messagingSenderId: '599526002290',
    projectId: 'newappblog',
    storageBucket: 'newappblog.appspot.com',
    iosClientId: '599526002290-ej0igm2g30irhrnhemh5hmls345ok7l9.apps.googleusercontent.com',
    iosBundleId: 'com.example.exblogapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChPNIJCFLjENnN2gvZf9imwJBP1TTf55c',
    appId: '1:599526002290:ios:d336424fa9667a24357ceb',
    messagingSenderId: '599526002290',
    projectId: 'newappblog',
    storageBucket: 'newappblog.appspot.com',
    iosClientId: '599526002290-ej0igm2g30irhrnhemh5hmls345ok7l9.apps.googleusercontent.com',
    iosBundleId: 'com.example.exblogapp',
  );
}
